wood:
  pose: [0.76, 0, -0.0073, 0, 0, 0, 1]
  size: [1.22, 0.915, 0.02, 0.05] # (dim_x, dim_y, dim_z_minus, dim_z_plus)
whiteboard:
  pose: [0.7, 0, 0.00465, 0, 0, 0, 1]
  size: [0.60, .90, 0.02, 0.02] # (dim_x, dim_y, dim_z_minus, dim_z_plus)
